version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/accounting_db
      - JWT_SECRET=A1TtQRD3b6bl4ye93kQl4HmziYF9H+ZvUUgemab/NExnE//sTFedayMBww6uJ68eRoKpLGAwDxI2CZqvd4WLKw==
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting_db
    volumes:
      - accounting_postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    restart: unless-stopped

volumes:
  accounting_postgres_data: