version: "3.9"

services:
  accounting-client:
    build:
      context: ./accountingclient
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
#      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - BACKEND_INTERNAL_URL=http://accounting-api:8080
    depends_on:
      - accounting-api
#    networks:
#      - app-network
  accounting-api:
    build:
      context: ./accountingapi
    ports:
      - "8888:8080"
    container_name: accounting-api-container
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=accounting
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ACCOUNTING_BOT_PASSWORD
    depends_on:
      - artemis
      - postgres

  accounting-bot:
    build:
      context: ./accountingbot
    container_name: accounting-bot-container
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ACTIVEMQ_USER=admin
      - ACTIVEMQ_PASSWORD=admin
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=accounting
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TELEGRAM_BOT_TOKEN
      - ACCOUNTING_BOT_PASSWORD
    depends_on:
      - artemis
      - redis

  postgres:
    image: postgres:17
    container_name: accounting-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=accounting
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: accounting-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  artemis:
    image: apache/activemq-artemis:2.41.0
    container_name: accounting-artemis-broker
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "61616:61616"   # порт для клиентов (JMS)
      - "8161:8161"     # веб-консоль (http://localhost:8161)
    volumes:
      - artemis-data:/var/lib/artemis/data

volumes:
  artemis-data:
  postgres-data:
  redis-data: