version: '3.8'

services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3001:3000"
#    environment:
#      - RUST_LOG=debug
#    restart: unless-stopped
#    depends_on:
#      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting_db
    volumes:
      - accounting_postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    restart: unless-stopped

volumes:
  accounting_postgres_data: