version: '3.8'

services:
  client:
    image: alexey195/accountingclient:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - db
      - api
  api:
    image: alexey195/accountingapi:latest
    ports:
      - "8888:8888"
    env_file:
      - .env-docker
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting_db
    volumes:
      - accounting_postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432"
    restart: unless-stopped

volumes:
  accounting_postgres_data: